services:
  - type: web
    name: ict-maintenance-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_ORIGINS
        value: https://smartcomputer-maintenance-system.netlify.app,https://smartcomputermaintenanceservice.netlify.app,http://localhost:3000,http://127.0.0.1:3000,http://localhost:5000,http://127.0.0.1:5000
      - key: MONGO_URI
        value: mongodb+srv://meseretayele611_db_user:mesi212123@ict-maintenance.xhanajl.mongodb.net/ict_maintenance_db?retryWrites=true&w=majority&appName=ICT-Maintenance
      - key: JWT_SECRET
        value: 2ed2585c3511d6f8824711bfea48e742d5bd4294af2bc6ecd82a2c7ae23bfbafd2d0553b66ee9f7681f6b7a1db6352d4
