const DeviceType = require("../models/DeviceType");

const DEVICE_TYPE_CATEGORIES = {
  "Desktop Computer": [
    "No Power",
    "Not Turning On",
    "Slow Performance",
    "Operating System",
    "Software Problem",
    "Hardware Problem",
    "Display Problem",
    "Keyboard Problem",
    "Mouse Problem",
    "Network/Internet",
    "Virus/Malware",
    "Driver Problem",
    "Overheating",
    "Upgrade Request",
    "Other",
  ],
  Laptop: [
    "No Power",
    "Not Turning On",
    "Battery Problem",
    "Charging Problem",
    "Screen/Display",
    "Keyboard Problem",
    "Touchpad Problem",
    "Operating System",
    "Software Problem",
    "Hardware Problem",
    "Network/Internet",
    "Wi-Fi Problem",
    "Driver Problem",
    "Overheating",
    "Upgrade Request",
    "Other",
  ],
  Tablet: [
    "No Power",
    "Battery Problem",
    "Charging Problem",
    "Screen/Display",
    "Touchscreen",
    "Operating System",
    "Software",
    "Wi-Fi",
    "Network",
    "Hardware",
    "Application Problem",
    "Other",
  ],
  "All-in-One Computer": [
    "No Power",
    "Display Problem",
    "Slow Performance",
    "Operating System",
    "Software",
    "Hardware",
    "Network/Internet",
    "Keyboard/Mouse",
    "Driver Problem",
    "Overheating",
    "Other",
  ],
  "Thin Client": [
    "No Power",
    "Boot Problem",
    "Network",
    "Server Connection",
    "Login Problem",
    "Configuration",
    "Software",
    "Hardware",
    "Other",
  ],
  Workstation: [
    "No Power",
    "Performance",
    "Operating System",
    "Software",
    "Hardware",
    "Graphics",
    "Storage",
    "Network",
    "Driver",
    "Upgrade",
    "Other",
  ],
  Monitor: [
    "No Display",
    "Flickering",
    "Poor Display Quality",
    "Screen Problem",
    "Power Problem",
    "HDMI Connection",
    "VGA Connection",
    "DisplayPort Connection",
    "Cable Problem",
    "Hardware",
    "Other",
  ],
  Keyboard: [
    "Not Working",
    "Keys Not Working",
    "Connection Problem",
    "USB Problem",
    "Wireless Problem",
    "Damaged Keys",
    "Hardware",
    "Replacement",
    "Other",
  ],
  Mouse: [
    "Not Working",
    "Cursor Problem",
    "Connection Problem",
    "USB Problem",
    "Wireless Problem",
    "Sensor Problem",
    "Hardware",
    "Replacement",
    "Other",
  ],
  Webcam: [
    "Not Detected",
    "No Video",
    "Poor Video Quality",
    "Microphone Problem",
    "USB Connection",
    "Driver Problem",
    "Software",
    "Hardware",
    "Other",
  ],
  Speakers: [
    "No Sound",
    "Low Sound",
    "Distorted Sound",
    "Connection",
    "USB",
    "Audio Driver",
    "Hardware",
    "Other",
  ],
  Headset: [
    "No Sound",
    "Microphone Problem",
    "Low Sound",
    "Distorted Sound",
    "Connection",
    "USB",
    "Bluetooth",
    "Hardware",
    "Other",
  ],
  Printer: [
    "Not Printing",
    "Paper Jam",
    "Poor Print Quality",
    "Ink/Toner",
    "No Ink/Toner",
    "Paper Feed Problem",
    "Network Printing",
    "USB Connection",
    "Driver Problem",
    "Configuration",
    "Hardware",
    "Maintenance",
    "Hardware Problem",
    "Other",
  ],
  Scanner: [
    "Not Scanning",
    "Poor Scan Quality",
    "Paper Feed Problem",
    "Connection Problem",
    "USB",
    "Network",
    "Driver Problem",
    "Software",
    "Hardware",
    "Maintenance",
    "Software Problem",
    "Hardware Problem",
    "Other",
  ],
  Photocopier: [
    "Not Copying",
    "Paper Jam",
    "Poor Copy Quality",
    "Toner",
    "Paper Feed",
    "Network",
    "Configuration",
    "Hardware",
    "Maintenance",
    "Other",
  ],
  "Multifunction Printer (MFP)": [
    "Printing Problem",
    "Scanning Problem",
    "Copying Problem",
    "Fax Problem",
    "Paper Jam",
    "Toner/Ink",
    "Network",
    "Driver",
    "Configuration",
    "Hardware",
    "Maintenance",
    "Other",
  ],
  Plotter: [
    "Not Printing",
    "Poor Print Quality",
    "Paper Problem",
    "Ink Problem",
    "Network",
    "Driver",
    "Configuration",
    "Hardware",
    "Maintenance",
    "Other",
  ],
  Projector: [
    "No Display",
    "Poor Display",
    "Lamp/Light Problem",
    "HDMI Problem",
    "VGA Problem",
    "Wireless Connection",
    "Remote Control",
    "Focus Problem",
    "Overheating",
    "Power Problem",
    "Hardware",
    "Other",
  ],
  "Interactive Display": [
    "No Display",
    "Touch Problem",
    "Calibration",
    "HDMI",
    "USB",
    "Network",
    "Software",
    "Configuration",
    "Hardware",
    "Other",
  ],
  "Smart Board": [
    "No Display",
    "Touch Problem",
    "Calibration",
    "Projector Connection",
    "USB",
    "Software",
    "Network",
    "Configuration",
    "Hardware",
    "Other",
  ],
  "Digital Display": [
    "No Display",
    "Poor Display",
    "Power",
    "HDMI",
    "Network",
    "Configuration",
    "Software",
    "Hardware",
    "Other",
  ],
  Router: [
    "No Internet",
    "WAN Problem",
    "LAN Problem",
    "Wi-Fi Problem",
    "Configuration",
    "IP Address",
    "DHCP",
    "DNS",
    "Routing",
    "Firmware",
    "Password/Authentication",
    "Connectivity",
    "Hardware",
    "VPN",
    "Authentication",
    "Hardware Problem",
    "Power Problem",
    "Other",
  ],
  Switch: [
    "Port Failure",
    "No Network Connection",
    "Configuration",
    "VLAN",
    "Trunk Problem",
    "Power Problem",
    "Firmware",
    "Network Loop",
    "Cable Connection",
    "Hardware",
    "Hardware Problem",
    "Other",
  ],
  Hub: [
    "Port Failure",
    "No Connection",
    "Network Problem",
    "Power Problem",
    "Cable Connection",
    "Hardware",
    "Connection Problem",
    "Hardware Problem",
    "Other",
  ],
  Modem: [
    "No Internet",
    "No Signal",
    "Connection Problem",
    "Configuration",
    "SIM/Network",
    "WAN",
    "Power Problem",
    "Firmware",
    "Hardware",
    "Hardware Problem",
    "Other",
  ],
  "Access Point": [
    "No Wi-Fi",
    "Weak Signal",
    "No Connection",
    "Configuration",
    "Authentication",
    "Password Problem",
    "IP Address",
    "Firmware",
    "Coverage Problem",
    "Hardware",
    "Hardware Problem",
    "Other",
  ],
  Firewall: [
    "Configuration",
    "Security Rule",
    "Access Control",
    "Network Connection",
    "VPN",
    "NAT",
    "Firewall Policy",
    "Authentication",
    "Firmware",
    "Hardware",
    "Security Problem",
    "Hardware Problem",
    "Other",
  ],
  "Network Cable": [
    "Damaged Cable",
    "No Connection",
    "Poor Connection",
    "Connector Problem",
    "Cable Testing",
    "Cable Installation",
    "Cable Replacement",
    "Wrong Cable",
    "Port Connection",
    "Other",
  ],
  "Patch Panel": [
    "Port Problem",
    "Cable Problem",
    "Labeling",
    "Connection",
    "Installation",
    "Maintenance",
    "Other",
  ],
  "Network Rack": [
    "Cable Management",
    "Rack Installation",
    "Power",
    "Cooling",
    "Physical Damage",
    "Organization",
    "Network Equipment",
    "Maintenance",
    "Other",
  ],
  "Network Adapter / NIC": [
    "Not Detected",
    "Network Connection",
    "Driver Problem",
    "Speed Problem",
    "Configuration",
    "Hardware",
    "Replacement",
    "Other",
  ],
  "Wi-Fi Device": [
    "No Connection",
    "Weak Signal",
    "Authentication",
    "Configuration",
    "Speed Problem",
    "Coverage",
    "Network",
    "Hardware",
    "Network Problem",
    "Hardware Problem",
    "Other",
  ],
  "Network Repeater / Extender": [
    "No Connection",
    "Weak Signal",
    "Configuration",
    "Coverage",
    "Authentication",
    "Power",
    "Firmware",
    "Hardware",
    "Other",
  ],
  "Load Balancer": [
    "Configuration",
    "Traffic Distribution",
    "Network",
    "Server Connection",
    "Health Check",
    "Performance",
    "Firmware",
    "Hardware",
    "Other",
  ],
  Server: [
    "Server Down",
    "Boot Problem",
    "Performance",
    "Storage",
    "Network",
    "Operating System",
    "Application",
    "Database",
    "Security",
    "Backup",
    "User Access",
    "Configuration",
    "Hardware",
    "Power",
    "Cooling",
    "Hardware Problem",
    "Power Problem",
    "Cooling Problem",
    "Other",
  ],
  "Server Rack": [
    "Rack Installation",
    "Cable Management",
    "Power",
    "Cooling",
    "Physical Damage",
    "Organization",
    "Maintenance",
    "Other",
  ],
  "NAS Storage": [
    "Storage Failure",
    "Disk Failure",
    "Network",
    "Backup",
    "File Access",
    "User Permission",
    "Configuration",
    "Performance",
    "Firmware",
    "Hardware",
    "Other",
  ],
  "Storage Device": [
    "Disk Failure",
    "Not Detected",
    "Storage Capacity",
    "Data Access",
    "Data Transfer",
    "Formatting",
    "Hardware",
    "Replacement",
    "Other",
  ],
  UPS: [
    "No Power",
    "Battery Problem",
    "Charging Problem",
    "Backup Failure",
    "Alarm",
    "Overload",
    "Power Output",
    "Battery Replacement",
    "Hardware",
    "Maintenance",
    "Hardware Problem",
    "Other",
  ],
  "Power Supply Unit (PSU)": [
    "No Power",
    "Power Failure",
    "Overheating",
    "Fan Problem",
    "Voltage Problem",
    "Hardware",
    "Replacement",
    "Other",
  ],
  "PoE Device": [
    "No Power",
    "PoE Port Problem",
    "Network Connection",
    "Configuration",
    "Power Output",
    "Overload",
    "Hardware",
    "Other",
  ],
  "IP Phone": [
    "No Power",
    "No Dial Tone",
    "Network",
    "SIP/VoIP",
    "Configuration",
    "Registration",
    "Audio Problem",
    "Microphone",
    "Speaker",
    "Firmware",
    "Hardware",
    "Hardware Problem",
    "Other",
  ],
  Telephone: [
    "No Dial Tone",
    "Connection",
    "Audio Problem",
    "Cable",
    "Extension",
    "Line Problem",
    "Hardware",
    "Hardware Problem",
    "Other",
  ],
  "VoIP Phone": [
    "No Power",
    "Network",
    "SIP",
    "Registration",
    "Configuration",
    "Audio",
    "Account",
    "Firmware",
    "Hardware",
    "Other",
  ],
  "Video Conferencing Device": [
    "No Video",
    "No Audio",
    "Camera Problem",
    "Microphone Problem",
    "Network",
    "Software",
    "Configuration",
    "Connection",
    "Hardware",
    "Other",
  ],
  Intercom: [
    "No Audio",
    "No Connection",
    "Power",
    "Cable",
    "Configuration",
    "Hardware",
    "Other",
  ],
  "CCTV Camera": [
    "No Video",
    "Poor Video Quality",
    "No Power",
    "Network",
    "Night Vision",
    "Camera Position",
    "Focus",
    "Configuration",
    "Cable",
    "Hardware",
    "Hardware Problem",
    "Other",
  ],
  "CCTV DVR": [
    "No Recording",
    "No Video",
    "Storage Failure",
    "Playback Problem",
    "Network",
    "Configuration",
    "Camera Connection",
    "Power",
    "Hardware",
    "Other",
  ],
  "CCTV NVR": [
    "No Recording",
    "No Video",
    "Storage Failure",
    "Playback Problem",
    "Network",
    "Configuration",
    "Camera Connection",
    "Power",
    "Hardware",
    "Other",
  ],
  "Biometric/Fingerprint Device": [
    "Not Working",
    "Fingerprint Recognition",
    "Enrollment",
    "User Registration",
    "Authentication",
    "Network",
    "Configuration",
    "Database",
    "Power",
    "Hardware",
    "Hardware Problem",
    "Other",
  ],
  "Access Control Device": [
    "Door Access",
    "Card Reader",
    "Fingerprint",
    "Authentication",
    "Network",
    "Configuration",
    "Power",
    "Lock Problem",
    "Hardware",
    "Other",
  ],
  "Door Access Controller": [
    "Door Not Opening",
    "Door Not Locking",
    "Card Problem",
    "Fingerprint Problem",
    "Network",
    "Configuration",
    "Power",
    "Hardware",
    "Other",
  ],
  "RFID/Card Reader": [
    "Card Not Detected",
    "Authentication",
    "Connection",
    "Network",
    "Configuration",
    "Power",
    "Hardware",
    "Other",
  ],
  "External Hard Drive": [
    "Not Detected",
    "Data Access",
    "Data Transfer",
    "Storage Failure",
    "Connection",
    "Formatting",
    "Hardware",
    "Other",
  ],
  "USB Flash Drive": [
    "Not Detected",
    "Data Access",
    "Data Transfer",
    "Formatting",
    "Corrupted Data",
    "Hardware",
    "Other",
  ],
  "CD/DVD Drive": [
    "Not Reading",
    "Not Writing",
    "Connection",
    "Driver",
    "Hardware",
    "Other",
  ],
  "Barcode Scanner": [
    "Not Scanning",
    "Poor Scan",
    "Connection",
    "USB",
    "Configuration",
    "Driver",
    "Hardware",
    "Other",
  ],
  "Card Printer": [
    "Not Printing",
    "Poor Print Quality",
    "Ribbon",
    "Card Feeding",
    "Connection",
    "Driver",
    "Configuration",
    "Hardware",
    "Other",
  ],
  Other: [
    "Hardware Problem",
    "Software Problem",
    "Network Problem",
    "Internet Problem",
    "Power Problem",
    "Configuration",
    "Installation",
    "Maintenance",
    "Upgrade",
    "Replacement",
    "Other",
  ],
};

const LEGACY_DEVICE_TYPE_CATEGORIES = {
  Network: DEVICE_TYPE_CATEGORIES.Router,
  "UPS / Power Supply": DEVICE_TYPE_CATEGORIES.UPS,
  "Keyboard / Mouse": [
    "Not Working",
    "Connection Problem",
    "USB Problem",
    "Wireless Problem",
    "Hardware",
    "Replacement",
    "Other",
  ],
  "Computer / Desktop": DEVICE_TYPE_CATEGORIES["Desktop Computer"],
  "Other Network Device": DEVICE_TYPE_CATEGORIES.Router,
  "Other ICT Device": DEVICE_TYPE_CATEGORIES.Other,
};

const CATALOG_CATEGORY_FALLBACKS = {
  "Computers & Computing Equipment": DEVICE_TYPE_CATEGORIES["Desktop Computer"],
  "Printing & Scanning": DEVICE_TYPE_CATEGORIES.Printer,
  "Display & Presentation": DEVICE_TYPE_CATEGORIES["Digital Display"],
  Networking: DEVICE_TYPE_CATEGORIES.Router,
  "Cables & Connectivity": DEVICE_TYPE_CATEGORIES["Network Cable"],
  "Power Equipment": DEVICE_TYPE_CATEGORIES.UPS,
  "Computer Accessories": DEVICE_TYPE_CATEGORIES.Keyboard,
  Communication: DEVICE_TYPE_CATEGORIES["IP Phone"],
  "Security & Surveillance": DEVICE_TYPE_CATEGORIES["CCTV Camera"],
  "Data Center": DEVICE_TYPE_CATEGORIES.Server,
  "IoT & Smart Devices": DEVICE_TYPE_CATEGORIES.Other,
  "Office & ICT Equipment": DEVICE_TYPE_CATEGORIES.Other,
  Other: DEVICE_TYPE_CATEGORIES.Other,
};

function getAllDeviceTypeCategories() {
  const categories = new Set([
    ...Object.values(DEVICE_TYPE_CATEGORIES).flat(),
    ...Object.values(LEGACY_DEVICE_TYPE_CATEGORIES).flat(),
    ...Object.values(CATALOG_CATEGORY_FALLBACKS).flat(),
  ]);
  categories.delete("Other");
  return [...categories, "Other"];
}

function getDeviceTypeCategories(deviceType, catalogCategory = null) {
  if (Object.hasOwn(DEVICE_TYPE_CATEGORIES, deviceType)) {
    return DEVICE_TYPE_CATEGORIES[deviceType];
  }
  if (Object.hasOwn(LEGACY_DEVICE_TYPE_CATEGORIES, deviceType)) {
    return LEGACY_DEVICE_TYPE_CATEGORIES[deviceType];
  }
  if (Object.hasOwn(CATALOG_CATEGORY_FALLBACKS, catalogCategory)) {
    return CATALOG_CATEGORY_FALLBACKS[catalogCategory];
  }
  return null;
}

async function resolveDeviceTypeCategories(deviceType) {
  if (typeof deviceType !== "string" || !deviceType.trim()) return null;

  const exactCategories = getDeviceTypeCategories(deviceType.trim());
  if (exactCategories) return exactCategories;

  const catalogType = await DeviceType.findOne({
    name: deviceType.trim(),
    active: true,
  })
    .select("category")
    .lean();

  return catalogType
    ? getDeviceTypeCategories(deviceType.trim(), catalogType.category)
    : null;
}

module.exports = {
  DEVICE_TYPE_CATEGORIES,
  getAllDeviceTypeCategories,
  getDeviceTypeCategories,
  resolveDeviceTypeCategories,
};
